services:
  landing-page:
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: packages/landing-page/Dockerfile
    environment:
      - NODE_ENV=development

  dashboard:
    build:
      context: .
      dockerfile: packages/dashboard/Dockerfile
    ports:
      - "5173:80"
    environment:
      - NODE_ENV=development
