export const NavLinksList = {
  LINK_EN: [
    { name: "Feature", url: "#feature" },
    // { name: 'Pricing', url: '#pricing' },
    // { name: 'Testimonial', url: '#testimonial' },
    // { name: "FAQ", url: "#faq" },
    { name: "How It Works", url: "#how-it-works" },
    // { name: "About", url: "/about" },
    // { name: 'Blog', url: '/blog' },
    { name: "Repositories", url: "/dash" },
  ], 
  LINK_ZH: [
    { name: "核心功能", url: "#feature" },
    // { name: '定价', url: '#pricing' },
    // { name: '评价', url: '#testimonial' },
    // { name: "常见问题", url: "#faq" },
    { name: "工作原理", url: "#how-it-works" },
    // { name: "关于", url: "/about" },
    // { name: '博客', url: '/blog' },
    { name: "仓库列表", url: "/dash" },
  ],
  LINK_ES: [
    { name: "Función", url: "#feature" },
    // { name: 'Precios', url: '#pricing' },
    // { name: 'Testimonio', url: '#testimonial' },
    // { name: "Preguntas Frecuentes", url: "#faq" },
    { name: "Cómo Funciona", url: "#how-it-works" },
    // { name: "Acerca de", url: "/about" },
    // { name: 'Blog', url: '/blog' },
    { name: "Repositorios", url: "/dash" },
  ],
  LINK_RU: [
    { name: "Функция", url: "#feature" },
    // { name: 'Цены', url: '#pricing' },
    // { name: 'Отзыв', url: '#testimonial' },
    // { name: "Часто задаваемые вопросы", url: "#faq" },
    { name: "Как это работает", url: "#how-it-works" },
    // { name: "О нас", url: "/about" },
    // { name: 'Блог', url: '/blog' },
    { name: "Репозитории", url: "/dash" },
  ],
  LINK_JA: [
    { name: "機能", url: "#feature" },
    // { name: '価格', url: '#pricing' },
    // { name: 'お客様の声', url: '#testimonial' },
    // { name: "よくある質問", url: "#faq" },
    { name: "仕組み", url: "#how-it-works" },
    // { name: "アバウト", url: "/about" },
    // { name: 'ブログ', url: '/blog' },
    { name: "リポジトリ", url: "/dash" },
  ],
  LINK_AR: [
    { name: "ميزة", url: "#feature" },
    // { name: 'التسعير', url: '#pricing' },
    // { name: 'شهادة', url: '#testimonial' },
    // { name: "الأسئلة الشائعة", url: "#faq" },
    { name: "كيف يعمل", url: "#how-it-works" },
    // { name: "حول", url: "/about" },
    // { name: 'مدونة', url: '/blog' },
    { name: "المستودعات", url: "/dash" },
  ],
  LINK_FR: [
    { name: "Fonctionnalité", url: "#feature" },
    // { name: 'Tarification', url: '#pricing' },
    // { name: 'Témoignages', url: '#testimonial' },
    // { name: "FAQ", url: "#faq" },
    { name: "Comment ça marche", url: "#how-it-works" },
    // { name: "À propos", url: "/about" },
    // { name: 'Blog', url: '/blog' },
    { name: "Dépôts", url: "/dash" },
  ],
};
