interface Repository {
  name: string;
  description: string;
  isPublic: boolean;
  language: string;
  stars: number;
  forks?: number;
  lastUpdated: string;
  license?: string;
}

// 添加模拟数据
export const mockRepositories: Repository[] = [
  {
    name: "react-awesome-app",
    description: "一个使用 React 和 TypeScript 构建的现代化应用程序",
    isPublic: true,
    language: "TypeScript",
    stars: 128,
    forks: 45,
    lastUpdated: "2024-03-15",
    license: "MIT",
  },
  {
    name: "vue-dashboard",
    description: "基于 Vue.js 的管理后台模板",
    isPublic: true,
    language: "Vue",
    stars: 89,
    forks: 23,
    lastUpdated: "2024-03-10",
  },
  {
    name: "node-api-starter",
    description: "Node.js REST API 启动模板，包含认证和数据库集成",
    isPublic: false,
    language: "JavaScript",
    stars: 256,
    forks: 67,
    lastUpdated: "2024-03-01",
    license: "Apache-2.0",
  },
  {
    name: "python-ml-toolkit",
    description: "机器学习工具集，包含常用算法实现",
    isPublic: true,
    language: "Python",
    stars: 432,
    forks: 89,
    lastUpdated: "2024-03-08",
    license: "MIT",
  },
  {
    name: "go-microservices",
    description: "基于 Go 的微服务架构示例",
    isPublic: true,
    language: "Go",
    stars: 367,
    forks: 78,
    lastUpdated: "2024-03-12",
    license: "MIT",
  },
  {
    name: "react-native-ui-kit",
    description: "React Native UI 组件库",
    isPublic: true,
    language: "TypeScript",
    stars: 892,
    forks: 156,
    lastUpdated: "2024-03-14",
    license: "MIT",
  },
  {
    name: "flutter-shop-app",
    description: "Flutter 电商应用模板",
    isPublic: true,
    language: "Dart",
    stars: 245,
    forks: 67,
    lastUpdated: "2024-03-09",
  },
  {
    name: "rust-blockchain",
    description: "使用 Rust 实现的区块链示例",
    isPublic: true,
    language: "Rust",
    stars: 567,
    forks: 89,
    lastUpdated: "2024-03-11",
    license: "MIT",
  },
  {
    name: "angular-crm",
    description: "企业级 CRM 系统前端实现",
    isPublic: false,
    language: "TypeScript",
    stars: 178,
    forks: 45,
    lastUpdated: "2024-03-07",
  },
  {
    name: "django-blog",
    description: "基于 Django 的博客系统",
    isPublic: true,
    language: "Python",
    stars: 156,
    forks: 34,
    lastUpdated: "2024-03-13",
    license: "MIT",
  },
  {
    name: "swift-weather-app",
    description: "iOS 天气应用",
    isPublic: true,
    language: "Swift",
    stars: 234,
    forks: 56,
    lastUpdated: "2024-03-06",
    license: "MIT",
  },
  {
    name: "kotlin-android-app",
    description: "Kotlin Android 应用模板",
    isPublic: true,
    language: "Kotlin",
    stars: 345,
    forks: 78,
    lastUpdated: "2024-03-05",
  },
  {
    name: "express-auth-service",
    description: "Express.js 认证服务",
    isPublic: false,
    language: "JavaScript",
    stars: 123,
    forks: 34,
    lastUpdated: "2024-03-04",
    license: "MIT",
  },
  {
    name: "spring-boot-starter",
    description: "Spring Boot 项目启动模板",
    isPublic: true,
    language: "Java",
    stars: 789,
    forks: 234,
    lastUpdated: "2024-03-03",
    license: "Apache-2.0",
  },
  {
    name: "php-cms",
    description: "PHP 内容管理系统",
    isPublic: true,
    language: "PHP",
    stars: 167,
    forks: 45,
    lastUpdated: "2024-03-02",
  },
  {
    name: "docker-compose-templates",
    description: "常用 Docker Compose 配置模板",
    isPublic: true,
    language: "Dockerfile",
    stars: 892,
    forks: 245,
    lastUpdated: "2024-03-01",
    license: "MIT",
  },
  {
    name: "nextjs-portfolio",
    description: "使用 Next.js 构建的个人作品集网站",
    isPublic: true,
    language: "TypeScript",
    stars: 234,
    forks: 67,
    lastUpdated: "2024-02-29",
  },
  {
    name: "unity-game-demo",
    description: "Unity 3D 游戏演示项目",
    isPublic: true,
    language: "C#",
    stars: 456,
    forks: 89,
    lastUpdated: "2024-02-28",
    license: "MIT",
  },
  {
    name: "laravel-ecommerce",
    description: "基于 Laravel 的电商平台",
    isPublic: false,
    language: "PHP",
    stars: 345,
    forks: 78,
    lastUpdated: "2024-02-27",
    license: "MIT",
  },
  {
    name: "tensorflow-examples",
    description: "TensorFlow 深度学习示例集",
    isPublic: true,
    language: "Python",
    stars: 1234,
    forks: 345,
    lastUpdated: "2024-02-26",
    license: "Apache-2.0",
  },
];
