// 需要过滤的文件扩展名
export const badExtensions = ['.log', '.tmp', '.bak', '.lock', '.png', '.jpg', '.jpeg', '.gif', '.webp', '.svg', '.ico'];

// 自动生成的文件名
export const autoGeneratedFiles = ['package-lock.json', 'yarn.lock', 'pnpm-lock.yaml'];

// 语言及其相关文件扩展名
export const languageExtensionMap = {
  java: ['.java'],
  python: ['.py'],
  javascript: ['.js', '.jsx'],
  typescript: ['.ts', '.tsx'],
  html: ['.html', '.htm'],
  css: ['.css', '.scss', '.sass', '.less'],
  json: ['.json'],
  yaml: ['.yaml', '.yml'],
  toml: ['.toml'],
  xml: ['.xml'],
  csv: ['.csv'],
  md: ['.md'],
  txt: ['.txt'],
};
